### ISSUE TITLE
Why not fork?

### ISSUE THREAD

**Issue by asharpe** [naingyeminn/CentOS7_Lockdown#1]
Seems you've forked https://github.com/rosshamilton1/cissec, but not using git.  This makes it harder to see what changes you've done, and also to submit changes upstream.

I'm just curious to see if there was a reason you chose not to do this?

**Comment by asharpe** [comment]
or https://github.com/gotojeffray/cissec, and the question remains :)

**Comment by naingyeminn** [comment]
Yes, I just downloaded from https://github.com/rosshamilton1/cissec and made changes without git because it was only for my own personal use. However, a friend asked me to share it back here. As I forgot the changes I made and didn't have much free time to contribute in upstream properly, I just created a new repo and shared as it is. I'm really sorry it turned out that way.
